src/4.Presentation/AYweb.Presentation/Controllers/BlogController.cs
using AYweb.Application.Models.Blog.Commands.AddBlogComment;
using AYweb.Application.Models.Blog.Queries.GetBlog;
using AYweb.Application.Models.Blog.Queries.GetBlogComments;
using AYweb.Application.Models.Blog.Queries.GetBlogGroups;
using AYweb.Application.Models.Blog.Queries.GetBlogs;
using AYweb.Application.Models.Blog.Queries.GetBlogsComments;
using AYweb.Application.Models.Blog.Queries.GetTags;
using AYweb.Domain.Models.Blog.Entities;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace AYweb.Presentation.Controllers
{
    public class BlogController : Controller
    {
        private readonly ISender _sender;

        public BlogController(ISender sender)
        {
            _sender = sender;
        }

        public IActionResult Index(int pageId = 1, string search = "")
        {
            int take = 8;

            var newsList = _sender.Send(new GetBlogsQuery { PageSize = take, PageNumber = pageId,search= search }).Result;

            ViewBag.pageId = pageId;

            if (pageId > 1)
            {
                ViewBag.lastPage = pageId - 1;
            }
            else
            {
                ViewBag.lastPage = 1;
            }

            if (pageId == newsList.calculatePageCount() || pageId > newsList.calculatePageCount())
            {
                ViewBag.nextPage = pageId;
            }
            else
            {
                ViewBag.nextPage = pageId + 1;
            }

            ViewBag.take = take;

            ViewData["tags"] = _sender.Send(new GetTagsQuery()).Result;
            ViewData["PopularNews"] = newsList.QueryResult;
            ViewData["NewsGroups"] = _sender.Send(new GetBlogGroupsQuery()).Result;
            ViewData["LastNews"] = newsList.QueryResult;
            ViewData["LastComment"] = _sender.Send(new GetBlogsCommentsQuery()).Result;

            return View(newsList);
        }

        public IActionResult BlogDetails(int id)
        {
            var news = _sender.Send(new GetBlogQuery { Id = id });

            if (news is null) return NotFound();

            var newsList = _sender.Send(new GetBlogsQuery { PageSize = 8, PageNumber = 1,search=""}).Result;//test

            if (news == null)
            {
                return NotFound();
            }

            ViewData["tags"] = _sender.Send(new GetTagsQuery()).Result;
            ViewData["PopularNews"] = newsList.QueryResult;
            ViewData["NewsGroups"] = _sender.Send(new GetBlogGroupsQuery()).Result;
            ViewData["LastNews"] = newsList.QueryResult;
            ViewData["LastComment"] = _sender.Send(new GetBlogsCommentsQuery()).Result;            
            return View(news.Result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddComment(AddBlogCommentCommand commentCommand)
        {
            var req = Request;
            _sender.Send(commentCommand);

            return RedirectToAction("BlogDetails", new { id = commentCommand.BlogId });
        }
    }
}

src/4.Presentation/AYweb.Presentation/Controllers/OrderController.cs
using AYweb.Application.Models.Order.Commands.ChnageOrderLineAmount;
using AYweb.Application.Models.Order.Commands.DeleteOrderLineFromOrder;
using AYweb.Application.Models.Order.Queries.GetCurrentUserCurrentOrder;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace AYweb.Presentation.Controllers
{
    public class OrderController : Controller
    {
        private readonly ISender _sender;

        public OrderController(ISender sender)
        {
            _sender = sender;
        }


        public IActionResult MyCart()
        {
            return View(_sender.Send(new GetCurrentUserCurrentOrderQuery()).Result);
        }

        [HttpPost]        
        public void ChangeOrderLineCount(long productId, int count)
        {
            //  _service.ChangeOrderLineCount(productId, count, HttpContext);
            _sender.Send(new ChnageOrderLineAmountCommand { ProductId = productId, Amount = count });
        }

        [HttpPost]
        public IActionResult DeleteOrderLine(long productId)
        {
            _sender.Send(new DeleteOrderLineFromOrderCommand() { productId = productId });
            return RedirectToAction("MyCart", "Index", new { area = "UserPanel" });
        }


    }
}

src/4.Presentation/AYweb.Presentation/Controllers/PlanController.cs
using AYweb.Application.Models.Plan.Queries.GetPlans;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AYweb.Presentation.Controllers
{
    public class PlanController : Controller
    {
        private readonly ISender _sender;

        public PlanController(ISender sender)
        {
            _sender = sender;
        }

        public IActionResult Index()
        {
            return View(_sender.Send(new GetPlansQuery()).Result);
        }       
    }
}

src/4.Presentation/AYweb.Presentation/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;

namespace AYweb.Presentation.Controllers
{
    public class ServiceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/4.Presentation/AYweb.Presentation/Views/Shared/MainLayout.cshtml
<!doctype html>

<html lang="fa">

<head>
    <!-- Required meta tags -->
    <partial name="_MetaTags" />
    @RenderSection("Styles", false)
    <partial name="_Styles" />
    <title>AY WEB - دنیای وب و برنامه نویسی</title>
    <link rel="icon" type="image/png" href="/img/fav.png">
</head>
<body>
    <partial name="_PreLoad" />

    <partial name="_Navbar" />

    <partial name="_SideBarModal" />

    @RenderBody()

    <partial name="_Footer" />
    <partial name="_Script" />
    @RenderSection("Scripts", false)
</body>

</html>

src/4.Presentation/AYweb.Presentation/Views/Shared/_Footer.cshtml
 <!-- Start Footer Area -->
<section class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h3>اطلاعات تماس</h3>

                    <ul class="footer-contact-info">
                        <li>
                            <i class="flaticon-phone-call"></i>
                            <a href="#">09966308993</a>
                            <br />
                            <a href="#">09134181998</a>
                        </li>
                        <li>
                            <i class="flaticon-email"></i>
                            <span>آیا سوالی دارید؟</span>
                            <a href="#">Support@ayweb.work</a>
                        </li>
                        <li>
                            <i class="flaticon-social-media"></i>
                            <span>شبکه اجتماعی</span>

                            <ul class="social">
                                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fab fa-youtube"></i></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="single-footer-widget pr-5">
                    <h3>دسترسی سریع</h3>

                    <ul class="footer-quick-links">
                        <li><a asp-controller="Home" asp-action="Index">صفحه اصلی</a></li>
                        <li><a asp-controller="Home" asp-action="AboutUs">درباره ما</a></li>
                        <li><a asp-controller="Blog" asp-action="Index">وبلاگ</a></li>
                        <li><a asp-controller="Home" asp-action="CallUs">تماس با ما</a></li>
                        <li><a asp-controller="Product" asp-action="Index">فروشگاه</a></li>                        
                        <li><a asp-controller="Service" asp-action="Index">خدمات</a></li>                                              
                    </ul>
                </div>

                <div class="single-footer-widget pr-5">
                    <h3>نماد ها</h3>

                    <ul class="footer-quick-links">
                        <li>
                            <a referrerpolicy='origin' target='_blank' href='https://trustseal.enamad.ir/?id=444348&Code=D1aD8E01253B3fea394e2f7AB462Cfa1'>
                                <img referrerpolicy='origin' src='/img/Enamad.png' alt='' style='cursor:pointer' Code='D1aD8E01253B3fea394e2f7AB462Cfa1'>
                            </a>
                        </li>                        
                    </ul>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-0 offset-md-3 offset-sm-3">
                <div class="single-footer-widget pr-5">
                    <h3>اینستاگرام</h3>

                    <ul class="footer-instagram-post">
                        <li>
                            <a href="#">
                                <img src="/img/instagram-image/1.jpg" alt="image">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/img/instagram-image/2.jpg" alt="image">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/img/instagram-image/3.jpg" alt="image">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/img/instagram-image/4.jpg" alt="image">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/img/instagram-image/5.jpg" alt="image">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/img/instagram-image/6.jpg" alt="image">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/img/instagram-image/7.jpg" alt="image">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/img/instagram-image/8.jpg" alt="image">
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="/img/instagram-image/1.jpg" alt="image">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="copyright-area">
            <div class="row align-items-center">
                <div class="col-lg-6 col-sm-6 col-md-6">
                    <p><i class="flaticon-copyright"></i> 1402 تمام حقوق قالب محفوظ است. طراحی و توسعه توسط <a href="/" target="_blank">AY WEB</a></p>

                </div>

                <div class="col-lg-6 col-sm-6 col-md-6">
                    <ul>
                        <li><a>شرایط و ضوابط</a></li>
                        <li><a>حریم خصوصی</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Footer Area -->

src/4.Presentation/AYweb.Presentation/Views/Shared/_MetaTags.cshtml
<meta name=”robots” content=”index, follow”>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="author" content="yasin abedini">

src/4.Presentation/AYweb.Presentation/Views/Shared/_Navbar.cshtml
@using AYweb.Application.Models.Order.Queries.GetCurrentUserCurrentOrder
@using AYweb.Application.Models.Plan.Queries.GetCurrentUserActivePlan
@using MediatR
@inject ISender _sender;

<!-- Start Navbar Area -->
<div class="navbar-area">
    <div class="aronix-responsive-nav">
        <div class="container">
            <div class="aronix-responsive-menu">
                <div class="logo">
                    <a asp-controller="Home" asp-action="Index">
                        <img src="/img/logo.png" alt="logo">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="aronix-nav">
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light">
                <a class="navbar-brand" asp-controller="home" asp-action="index">
                    <img src="/img/logo.png" alt="logo">
                </a>

                <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link active">
                                خانه <i class="fas "></i>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-controller="Plan" asp-action="Index" class="nav-link">
                                خرید اشتراک
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-controller="Service" asp-action="Index" class="nav-link">
                                خدمات
                            </a>
                        </li>


                        <li class="nav-item">
                            <a asp-controller="Product" asp-action="Index" class="nav-link">
                                فروشگاه <i class="fas"></i>
                            </a>
                        </li>

                      
                        <li class="nav-item">
                            <a asp-controller="Blog" asp-action="Index" class="nav-link">
                                وبلاگ <i class="fas "></i>
                            </a>
                        </li>
                        
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    حساب کاربری <i class="fas fa-chevron-down"></i>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a asp-area="UserPanel" asp-controller="Profile" asp-action="Profile" class="text-secondary fw-bolder nav-link">@Context.User.Identity.Name</a>
                                        <span class="text-muted fw-bold">( @_sender.Send(new GetCurrentUserActivePlanQuery()).Result.Title)</span>
                                    </li>
                                    <hr />
                                    <li class="nav-item">
                                        <a asp-area="UserPanel" asp-controller="Profile" asp-action="Profile" class="nav-link">پنل کاربری</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-area="UserPanel" asp-controller="Order" asp-action="Index" class="nav-link">سفارشات</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-area="UserPanel" asp-controller="Transaction" asp-action="Index" class="nav-link">پرداختی ها</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="Account" asp-action="LogOut" class="nav-link text-danger">خروج</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Login" class="nav-link">
                                  ورود / ثبت نام <i class="fas ="></i>
                                </a>
                            </li>
                        }
                       
                    </ul>



                    <div class="others-options">
                        <div class="cart-items">
                            <a asp-controller="Order" asp-action="MyCart">
                                <i class="fas fa-shopping-cart"></i>
                                @if (_sender.Send(new GetCurrentUserCurrentOrderQuery()).Result!=null)
                                {
                                    <span>@_sender.Send(new GetCurrentUserCurrentOrderQuery()).Result.OrderLines.Count</span>
                                }
                            </a>
                        </div>

                        <div class="option-item">
                            <i class="search-btn flaticon-search"></i>
                            <i class="close-btn flaticon-close"></i>

                            <div class="search-overlay search-popup">
                                <div class='search-box'>
                                    <form class="search-form">
                                        <input class="search-input" name="search" placeholder="جستجو" type="text">

                                        <button class="search-button" type="submit"><i class="fas fa-search"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="burger-menu">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- End Navbar Area -->

src/4.Presentation/AYweb.Presentation/Views/Shared/_PreLoad.cshtml
<div class="preloader">
    <div class="loader">
        <div class="shadow"></div>
        <div class="box"></div>
    </div>
</div>

src/4.Presentation/AYweb.Presentation/Views/Shared/_Script.cshtml
<!-- jQuery Min JS -->
<script src="/js/jquery.min.js"></script>
<!-- Popper Min JS -->
<script src="/js/popper.min.js"></script>
<!-- Bootstrap Min JS -->
<script src="/js/bootstrap.min.js"></script>
<!-- MeanMenu JS  -->
<script src="/js/jquery.meanmenu.js"></script>
<!-- Appear Min JS -->
<script src="/js/jquery.appear.min.js"></script>
<!-- Odometer Min JS -->
<script src="/js/odometer.min.js"></script>
<!-- Owl Carousel Min JS -->
<script src="/js/owl.carousel.min.js"></script>
<!-- Magnific Popup Min JS -->
<script src="/js/jquery.magnific-popup.min.js"></script>
<!-- Parallax Min JS -->
<script src="/js/parallax.min.js"></script>
<!-- Nice Select Min JS -->
<script src="/js/jquery.nice-select.min.js"></script>
<!-- WOW Min JS -->
<script src="/js/wow.min.js"></script>
<!-- AjaxChimp Min JS -->
<script src="/js/jquery.ajaxchimp.min.js"></script>
<!-- Form Validator Min JS -->
<script src="/js/form-validator.min.js"></script>
<!-- Contact Form Min JS -->
<script src="/js/contact-form-script.js"></script>
<!-- Main JS -->
<script src="/js/main.js"></script>
<!-- Custom JS -->
<script src="js/Script.js"></script>
<script src="/js/notify.js"></script>

src/4.Presentation/AYweb.Presentation/Views/Shared/_Shapes.cshtml
<div class="shape-img2"><img src="/img/shape/2.svg" alt="image"></div>
<div class="shape-img2"><img src="/img/shape/2.svg" alt="image"></div>
<div class="shape-img3"><img src="/img/shape/3.svg" alt="image"></div>
<div class="shape-img4"><img src="/img/shape/4.png" alt="image"></div>
<div class="shape-img5"><img src="/img/shape/5.png" alt="image"></div>
<div class="shape-img7"><img src="/img/shape/7.png" alt="image"></div>
<div class="shape-img8"><img src="/img/shape/8.png" alt="image"></div>
<div class="shape-img9"><img src="/img/shape/9.png" alt="image"></div>
<div class="shape-img10"><img src="/img/shape/10.png" alt="image"></div>

src/4.Presentation/AYweb.Presentation/Views/Shared/_SideBarModal.cshtml
<div class="sidebar-modal">
    <div class="sidebar-modal-inner">
        <div class="sidebar-about-area">
            <div class="title">
                <h2>درباره ما</h2>
                <p>تیم برنامه نویسی آی وب قراره به کلی کسب و کار کوچک و بزرگ آنلاین کمک کنه که کسب و کار خودشون رو توی وبسایت ادامه دهند و کلی ایده کوچک و بزرگ برای رشد کسب و کارشون از آی وب بگیرند. </p>
            </div>
        </div>

        <div class="sidebar-instagram-feed">
            <h2>اینستاگرام</h2>

            <ul>
                <li><a href="#"><img src="/img/blog-image/1.jpg" alt="image"></a></li>
                <li><a href="#"><img src="/img/blog-image/2.jpg" alt="image"></a></li>
                <li><a href="#"><img src="/img/blog-image/3.jpg" alt="image"></a></li>
                <li><a href="#"><img src="/img/blog-image/4.jpg" alt="image"></a></li>
                <li><a href="#"><img src="/img/blog-image/5.jpg" alt="image"></a></li>
                <li><a href="#"><img src="/img/blog-image/6.jpg" alt="image"></a></li>
                <li><a href="#"><img src="/img/blog-image/7.jpg" alt="image"></a></li>
                <li><a href="#"><img src="/img/blog-image/8.jpg" alt="image"></a></li>
            </ul>
        </div>

        <div class="sidebar-contact-area">
            <div class="contact-info">
                <div class="contact-info-content">
                    <h2>
                        <a href="tel:+989966308993">09966308993</a> /
                        <a href="tel:+9134181998" style="color:#0000ff !important">09134181998</a>
                        <span>یا</span>
                        <a href="mailto:Support@ayweb.work">Support@ayweb.work</a>
                    </h2>

                    <ul class="social">
                        <li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-youtube"></i></a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>

        <span class="close-btn sidebar-modal-close-btn"><i class="flaticon-close"></i></span>
    </div>
</div>

src/4.Presentation/AYweb.Presentation/Views/Shared/_Styles.cshtml
<!-- Bootstrap Min CSS -->
<link rel="stylesheet" href="/css/bootstrap.min.css">
<!-- Animate Min CSS -->
<link rel="stylesheet" href="/css/animate.min.css">
<!-- FlatIcon CSS -->
<link rel="stylesheet" href="/css/flaticon.css">
<!-- Odometer Min CSS -->
<link rel="stylesheet" href="/css/odometer.min.css">
<!-- MeanMenu CSS -->
<link rel="stylesheet" href="/css/meanmenu.css">
<!-- Magnific Popup Min CSS -->
<link rel="stylesheet" href="/css/magnific-popup.min.css">
<!-- Nice Select Min CSS -->
<link rel="stylesheet" href="/css/nice-select.min.css">
<!-- Owl Carousel Min CSS -->
<link rel="stylesheet" href="/css/owl.carousel.min.css">
<!-- Font Awesome Min CSS -->
<link rel="stylesheet" href="/css/fontawesome.min.css">
<!-- Boxicons CSS -->
<link rel="stylesheet" href="/css/boxicons.min.css">
<!-- Style CSS -->
<link rel="stylesheet" href="/css/style.css">
<!-- RTL CSS -->
<link rel="stylesheet" href="/css/rtl.css">
<!-- Responsive CSS -->
<link rel="stylesheet" href="/css/responsive.css">
<!-- Custom CSS -->
<link rel="stylesheet" href="/css/CustomStyle.css">